name: Azutoru
author: Aztl
api-version: 1.16
version: 1.0.0
main: me.aztl.azutoru.Azutoru
depend: [ProjectKorra]
softdepend: [JedCore]
permissions:
  azutoru.player:
    default: true
    children:
      bending.ability.aircocoon: true
      bending.ability.aircushion: true
      bending.ability.airspoutrush: true
      bending.ability.airvortex: true
      bending.ability.airwake: true
      bending.ability.cloudsurf: true
      bending.ability.dodge: true
      bending.ability.duck: true
      bending.ability.parry: true
      bending.ability.sandstorm: true
      bending.ability.metalcables: true
      bending.ability.lavawalk: true
      bending.ability.earthshield: true
      bending.ability.dustdevil: true
      bending.ability.dustdevilrush: true
      bending.ability.duststepping: true
      bending.ability.crumble: true
      bending.ability.earthshift: true
      bending.ability.earthtent: true
      bending.ability.glassshards: true
      bending.ability.earthridge: true
      bending.ability.raiseearth: true
      bending.ability.shockwave: true
      bending.ability.electrify: true
      bending.ability.evaporate: true
      bending.ability.fireaugmentation: true
      bending.ability.fireblade: true
      bending.ability.firebreath: true
      bending.ability.firestreams: true
      bending.ability.jetblast: true
      bending.ability.jetblaze: true
      bending.ability.jetstepping: true
      bending.ability.firedaggers: true
      bending.ability.firejet: true
      bending.ability.electricfield: true
      bending.ability.firewhips: true
      bending.ability.meteor: true
      bending.ability.shot: true
      bending.ability.iceshots: true
      bending.ability.miststepping: true
      bending.ability.iceridge: true
      bending.ability.razorrings: true
      bending.ability.waterpinwheel: true
      bending.ability.waterrun: true
      bending.ability.waterslash: true
      bending.ability.watersphere: true
      bending.ability.waterspoutrush: true
      bending.ability.watervortex: true
      bending.ability.octopusform: true
      bending.ability.transform: true
      bending.ability.bloodstrangle: true
      bending.ability.healinghands: true
      bending.ability.hexapod: true
      bending.ability.plantwhip: true
      bending.ability.watercanvas: true